# Site Info
title:              "K. A."
description:        "A raw guy programmer, ex-bioinformatician."
url:                "//www.artifactsauce.info"
google_verify:      z7WSt9rmDWQDbnAC3ZnPX--m6Ijw1QR29UrCvte7v8k
google_analytics:   UA-403364-11
logo:               https://www.gravatar.com/avatar/91282e22a7b16331c49c8d47eafcac14?s=270
show_downloads:     false

# Site Settings
baseurl:            "" # Base URL must end WITHOUT a slash, default: ""
permalink:          /posts/:year/:month/:day/:title
timezone:           Asia/Tokyo

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
encoding:           UTF-8
hard_wrap:          false

# Other Params
theme:              jekyll-theme-minimal
include:            [  ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "Gemfile.lock" ]
