# Site Info
title:              "Kenji Akiyama"
description:        "Software Developer, Web Developer, Server Engineer, ex-Bioinformatician."
google_verify:      z7WSt9rmDWQDbnAC3ZnPX--m6Ijw1QR29UrCvte7v8k
google_analytics:   UA-403364-11

# Author Info
author_name:        "Kenji Akiyama"
author_email:       artifactsauce@gmail.com
author_gravatar:    91282e22a7b16331c49c8d47eafcac14
twitter_username:   artifactsauce

# Site Settings
baseurl:            "" # Base URL must end WITHOUT a slash, default: ""
permalink:          /posts/:title
timezone:           Asia/Tokyo

# Site Build
highlighter:        pygments
#markdown:           redcarpet
#redcarpet:
#    extensions:     ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "highlight", "footnotes"]
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
gems:
  - jekyll-sitemap

compress_html:
    clippings:      all
    ingore:
        envs:       [ "test" ]

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
