# Site Info
title:              "Kenji Akiyama's Blog"
description:        "A raw guy programmer, ex-Bioinformatician."
url:                "//www.artifactsauce.info"
google_verify:      z7WSt9rmDWQDbnAC3ZnPX--m6Ijw1QR29UrCvte7v8k
google_analytics:   UA-403364-11

# Author Info
author_gravatar:    91282e22a7b16331c49c8d47eafcac14
twitter_username:   artifactsauce

# Site Settings
baseurl:            "" # Base URL must end WITHOUT a slash, default: ""
permalink:          /posts/:year/:month/:day/:title
timezone:           Asia/Tokyo

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "Gemfile.lock" ]
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jemoji

compress_html:
    clippings:      all
    ingore:
        envs:       [ "test" ]

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
